// Code generated by "stringer -type=PadAction -trimprefix=PadAction"; DO NOT EDIT.

package mikro

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PadActionPressed-1]
	_ = x[PadActionReleased-2]
	_ = x[PadActionReleased2-3]
	_ = x[PadActionTouched-4]
}

const _PadAction_name = "PressedReleasedReleased2Touched"

var _PadAction_index = [...]uint8{0, 7, 15, 24, 31}

func (i PadAction) String() string {
	i -= 1
	if i >= PadAction(len(_PadAction_index)-1) {
		return "PadAction(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _PadAction_name[_PadAction_index[i]:_PadAction_index[i+1]]
}
